# Generated by Django 2.2.9 on 2019-12-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='licence_file',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
