# Generated by Django 2.2.9 on 2019-12-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce_app', '0002_doctor_licence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='male', max_length=255),
        ),
        migrations.AlterField(
            model_name='cure',
            name='daily_consume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='total_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='vote_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
